@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.ticketfinder.dao.UserDaoDB",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_700473290 { 
   	label=ticketfinder
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CustomerUserDetailsService919722421[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CustomerUserDetailsService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   userDaoDB: UserDaoDB [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ loadUserByUsername(email: String): UserDetails</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OrderController26575897[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   concertDao: ConcertDao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   orderDao: OrderDao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   userDao: UserDao [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addOrder(request: HttpServletRequest): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteOrder(request: HttpServletRequest): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ orderList(model: Model): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserController26575897[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   concertDao: ConcertDao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   userDao: UserDao [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ admin(model: Model): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ createAccount(model: Model): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUser(user: User, result: BindingResult, model: Model): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ home(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ signIn(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ signOut(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserDaoDB172926553[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserDaoDB</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   jdbc: JdbcTemplate [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addUser(user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByEmail(username: String): User</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
CustomerUserDetailsService919722421 -> UserDaoDB172926553[label="userDaoDB
[1]"];
OrderController26575897 -> UserDaoDB172926553[label="userDao
[1]", arrowhead=none];
UserController26575897 -> UserDaoDB172926553[label="userDao
[1]", arrowhead=none];
    
}
@enduml